# this is the folder naming in Program Files.  It's a little different from how Intel
#     name their conda packages.
compiler_version:
  - 2022.1.0

# This is to keep consistent with Intel's conda package naming
intel_fortran_version:
  - 2022.1.0

zip_keys:
  - compiler_version
  - intel_fortran_version

# necessary to build until updated on main cbc
fortran_compiler_version:       # [win]
  - 2022.1.0                    # [win]
