# cuda 9.2, gcc 7.3, cudnn 7.6
# cuda 10.0, gcc 7.3, cudnn 7.6
# cuda 10.1, gcc 7.3, cudnn 7.6
c_compiler_version:           # [linux]
  - 7.3                       # [linux]
c_compiler_version:           # [osx]
  - 10                        # [osx]
cxx_compiler_version:         # [linux]
  - 7.3                       # [linux]
cxx_compiler_version:         # [osx]
  - 10                        # [osx]
cross_compiler_target_platform:   # [win]
  - win-64                        # [win]
target_platform:                  # [win]
  - win-64                        # [win]
cudatoolkit:
  - 10.1
cudnn:
  - 7.6
blas_impl:
  - mkl                        # [x86 or x86_64]
openblas:
  - 0.3.3
mkl:
  - 2019
numpy:
  - 1.11
python:
# - 2.7
# - 3.6
  - 3.7
pytorch_variant:
  - cpu
# - gpu
