# cuda 8.0, gcc 5.4, cudnn 7.1
# cuda 9.0, gcc 5.4, cudnn 7.3
# cuda 9.2, gcc 7.3, cudnn 7.3
# cuda 10.0, gcc 7.3, cudnn 7.3
c_compiler_version:
  - 5.4
cxx_compiler_version:
  - 5.4
cudatoolkit:
  - 9.0
cudnn:
  - 7.3
mkl:
  - 2019
python:
  - 3.6
