name: Auto-merge Update submodules PRs opened from anaconda/aggregate-duct-tape 
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.user.login == 'anacondarecipe-pr-service-account' &&
      contains(github.event.pull_request.labels.*.name, 'aggregate-duct-tape') &&
      contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}